cluster_name = "john-k8s"
aws_region = "us-east-1"
ami_id = "ami-1234567890"
public_subnet_ids = ["subnet-123", "subnet-456", "subnet-789"]
control_plane_iam_role = ""
control_plane_sg_ids = ["sg-123"]
worker_node_iam_role = ""
worker_node_sg_ids = ["sg-456"]
key_pair_name = ""
instance_type = "t3.medium"
