apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: mongo-init
          image: mongo:5
          command: ["sh", "-c"]
          args:
            - |
              until mongosh --host mongo-replica-set-mongo-0.mongodb-headless.default.svc.cluster.local:27017 --eval "print('MongoDB is up')" >/dev/null 2>&1; do 
                sleep 10
              done 

              mongosh --host mongo-replica-set-mongo-0.mongodb-headless.default.svc.cluster.local:27017 --eval '
              rs.initiate({ 
                _id: "myReplicaSet", 
                members: [ 
                  { _id: 0, host: "mongo-replica-set-mongo-0.mongodb-headless.default.svc.cluster.local:27017", priority: 2 }, 
                  { _id: 1, host: "mongo-replica-set-mongo-1.mongodb-headless.default.svc.cluster.local:27017", priority: 1 }, 
                  { _id: 2, host: "mongo-replica-set-mongo-2.mongodb-headless.default.svc.cluster.local:27017", priority: 1 } 
                ] 
              })'