apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo1
  labels:
    app: mongo
    instance: mongo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      instance: mongo1
  template:
    metadata:
      labels:
        app: mongo
        instance: mongo1
    spec:
      containers:
        - name: mongo
          image: {{ .Values.image }}:{{ .Values.imageTag }}
          ports:
            - containerPort: 27017
          command:
            - mongod
            - --replSet
            - {{ .Values.replicaSetName }}
            - --bind_ip
            - localhost,$(hostname)
          volumeMounts:
            - name: mongo1-data
              mountPath: /data/db
      volumes:
        - name: mongo1-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mongo1-pvc