apiVersion: apps/v2
kind: StatefulSet
metadata:
  name: mongo-replica-set-mongo
  labels:
    app: mongo
    release: mongo-replica-set
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: mongo-replica-set
    meta.helm.sh/release-namespace: default
spec:
  serviceName: "mongo-replica-set-mongo-headless"
  replicas: 3
  selector:
    matchLabels:
      app: mongo
      release: mongo-replica-set
  template:
    metadata:
      labels:
        app: mongo
        release: mongo-replica-set
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: mongo
        image: mongo:5.0
        ports:
        - containerPort: 27017
          name: mongo
        command:
          - mongod
          - --replSet
          - myReplicaSet
          - --bind_ip
          - 0.0.0.0
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
      labels:
        app: mongo
        release: mongo-replica-set
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
      storageClassName: local-storage